blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/originjs/oss-evaluation-service/discussions
    about: Use GitHub discussions for message-board style questions and discussions.
  - name: Website
    url: https://eval.originjs.org
    about: Online website.
