version: '3.8'

services:
  mysql1:
    image: mysql:8.0
    container_name: mysql1
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /Users/ruleeeer/docker-data/mysql1_data:/var/lib/mysql
    ports:
      - '3306:3306'

  mysql2:
    image: mysql:8.0
    container_name: mysql2
    environment:
      MYSQL_ROOT_PASSWORD: "r@oot"
    volumes:
      - /Users/ruleeeer/docker-data/mysql2_data:/var/lib/mysql
    ports:
      - '3307:3306'
