name: Deploy to Cloud Server

on:
  push:
    branches:
      - release
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'


      - name: Install npm dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run build task
        env:
            VITE_BACKEND_SERVICE_URL: ${{ secrets.BACKEND_SERVICE_URL }}
        run: |
          pnpm build-share
          pnpm build-api-server
          pnpm build-website

      - name: Deploy Website 🚀
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.HW_SSH_PRIVATE_KEY }}
          ARGS: "-avz --delete"
          SOURCE: "./"  # 更改为你要部署的文件夹
          TARGET: "/home/oss-eval-website/oss-evaluation-service/"
          EXCLUDE: "/node_modules/"
          REMOTE_HOST: ${{ secrets.HW_HOST }}
          REMOTE_USER: ${{ secrets.HW_USER }}
          REMOTE_PORT: ${{ secrets.HW_PORT }}  # 如果不是默认的22端口，需要更改
          SCRIPT_BEFORE: ls
          SCRIPT_AFTER: bash /home/ci_deploy.sh

      - name: Deploy Integration 🚀
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.BT_SSH_PRIVATE_KEY }}
          ARGS: "-avz --delete"
          SOURCE: "./"  # 更改为你要部署的文件夹
          TARGET: "/home/oss-eval-integration/oss-evaluation-service/"
          EXCLUDE: "/node_modules/"
          REMOTE_HOST: ${{ secrets.BT_HOST }}
          REMOTE_USER: ${{ secrets.BT_USER }}
          REMOTE_PORT: ${{ secrets.BT_PORT }}  # 如果不是默认的22端口，需要更改
          SCRIPT_BEFORE: ls
          SCRIPT_AFTER: bash /home/ci_deploy.sh